[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.5"
env_logger = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = "1"
